# Generated by Cascade on 2026-01-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payguard", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="paymentmethod",
                    name="wallet_id",
                ),
                migrations.AddField(
                    model_name="paymentmethod",
                    name="wallet",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="payguard.wallet",
                        db_column="wallet_id",
                    ),
                ),
                migrations.RemoveField(
                    model_name="transaction",
                    name="wallet_id",
                ),
                migrations.AddField(
                    model_name="transaction",
                    name="wallet",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payguard.wallet",
                        db_column="wallet_id",
                    ),
                ),
            ],
        ),
    ]
