# Generated by Django 5.2.10 on 2026-01-16 08:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipstream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='estimated_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ExchangeShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_number', models.CharField(max_length=50, unique=True)),
                ('exchange_date', models.DateField()),
                ('new_item', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('original_shipment', models.ForeignKey(db_column='original_awb', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_shipments', to='shipstream.shipment', to_field='tracking_number')),
            ],
        ),
        migrations.CreateModel(
            name='NdrEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndr_number', models.CharField(max_length=50, unique=True)),
                ('ndr_date', models.DateField()),
                ('issue', models.CharField(max_length=200)),
                ('attempts', models.IntegerField(default=1)),
                ('final_outcome', models.CharField(max_length=50)),
                ('original_shipment', models.ForeignKey(db_column='original_awb', on_delete=django.db.models.deletion.CASCADE, related_name='ndr_events', to='shipstream.shipment', to_field='tracking_number')),
            ],
        ),
        migrations.CreateModel(
            name='ReverseShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reverse_number', models.CharField(max_length=50, unique=True)),
                ('return_date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('refund_status', models.CharField(max_length=50)),
                ('original_shipment', models.ForeignKey(db_column='original_awb', on_delete=django.db.models.deletion.CASCADE, related_name='reverse_shipments', to='shipstream.shipment', to_field='tracking_number')),
            ],
        ),
    ]
