# Generated by Django 5.2.10 on 2026-01-17 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipstream', '0002_shipment_amount_shipment_customer_name_and_more'),
        ('shopcore', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shopcore.order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='estimated_arrival',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
