# Generated by Django 5.2.10 on 2026-01-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipstream', '0003_remove_shipment_order_id_shipment_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(default='', max_length=50, unique=True)),
                ('tracking_number', models.CharField(default='', max_length=50)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image_blob', models.BinaryField(blank=True, null=True)),
                ('image_mime_type', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='Initiated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
