# Generated by Django 5.2.10 on 2026-01-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipstream", "0004_returnrequest"),
        ("shopcore", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="shopcore.order",
                db_constraint=False,
            ),
        ),
    ]
